// Files that `projectmind init` writes for the AI tools other than Claude Code: portable skills
// (Agent Skills standard: name, description, metadata only), Gemini CLI commands and the
// AGENTS.md block. They call ProjectMind through npx, so they need nothing else installed.
// Every file carries the word "projectmind", which `projectmind uninstall` looks for.

export const BLOCK_START = '<!-- projectmind:start -->';
export const BLOCK_END = '<!-- projectmind:end -->';
export const SKILLS = ['remember', 'why', 'release-check'];

const skill = (name, description, body) => `---
name: projectmind-${name}
description: ${description}
metadata:
  generated-by: projectmind
---

${body.trim()}
`;

export function skillFile(name, cli) {
  if (name === 'remember') {
    return skill('remember', 'Records a project decision in docs/decisions/ as a numbered ADR, with the files it protects, the reason and the rejected alternatives. Use only when the user asks to record a decision.', `
# Record a decision

You propose, the user approves. Nothing is written without an explicit "yes" from them in the chat.
Do not invent a reason, a file or an alternative: whatever the conversation or the repository does not say, ask for it.
Do not choose the ADR number: the tool computes it. Reply in the user's language.

## 1. Check what already exists

Run \`${cli} adr list\` at the project root. If an ADR already covers the topic, cite it and ask
whether a new one is needed. If the project keeps decisions elsewhere (cited in AGENTS.md or the
README), say so: no duplicate without agreement.

## 2. Prepare the fields

A JSON object with: \`title\` (one short line), \`reason\` (one or two sentences, shown to whoever
touches a protected file), \`protected_files\` (paths or glob patterns relative to the project root:
\`*\` stays within a folder, \`**\` crosses folders, a path without wildcards also covers what it
contains; check that they match existing files; empty list if none), \`rejected_alternatives\`
(each with its reason in a few words), \`context\`, \`decision\`, and optionally \`options\` and
\`consequences\`.

## 3. Show the preview

Write the JSON object to a temporary file (outside the project if you can), then run
\`${cli} adr create --dry-run --input <that file>\`. It writes nothing. Show the output as is and
ask: "Shall I record this ADR?". If the user corrects a point, redo the preview.

## 4. Write, only after agreement

Run the same command without \`--dry-run\`, give the path of the created file, and delete the
temporary file. Do not commit or push.
`);
  }
  if (name === 'why') {
    return skill('why', 'Shows what the project knows about a file: the ADRs that protect or cite it, its mentions in the documentation and its last commits, each with its source. Use when the user asks why a file is the way it is, or before changing a file that a decision may protect.', `
# Why this file?

Do not modify any file. Reply in the user's language.

1. Run \`${cli} why "<file>"\` at the project root, with the path as the user gave it.
2. Show the output as is.
3. Add a summary of three sentences at most, drawn only from what the output cites. Each claim
   points to its source: \`ADR-001\`, \`DEBT.md:110\`, commit \`a1b2c3d\`.
4. If the output finds nothing, say so in one sentence. Do not invent a reason.
`);
  }
  return skill('release-check', 'Runs a ✓/⚠/✗ report before releasing a branch: the project\'s check command, the ADRs and protected files it touches, and secrets in what it adds. Use when the user asks whether a branch is ready to ship.', `
# Release check

Fix nothing, commit nothing, push nothing, do not fetch. Reply in the user's language.

1. Run \`${cli} release-check\` at the project root, with the options the user gave
   (\`--base <ref>\`, \`--check "<command>"\`, \`--no-check\`). Allow up to 10 minutes: the project's
   check command may be long.
2. Show the report as is.
3. For each ✗ and each ⚠, one sentence: what it means and what to do. To understand a failing
   command, read the full log named in the report.
4. Secrets: never open a reported line, never read or repeat its value. Say where it is, and that
   it must be revoked and then removed from history.
5. End with the report's verdict, without softening it.
`);
}

const TOML_DESCRIPTIONS = {
  remember: 'Record a project decision as an ADR (ProjectMind)',
  why: 'What the project knows about a file (ProjectMind)',
  'release-check': 'Release check of the current branch (ProjectMind)',
};

// Gemini CLI has no slash command for skills: one command per skill, which points to it.
export const geminiCommand = (name) => `# Generated by projectmind init.
description = ${JSON.stringify(TOML_DESCRIPTIONS[name])}
prompt = """
Follow the instructions of .agents/skills/projectmind-${name}/SKILL.md, with: {{args}}
"""
`;

export const agentsBlock = (cli) => `${BLOCK_START}
## Project decisions (ProjectMind)

This project records its decisions as ADRs in \`docs/decisions/\`. Before changing a file, check
what the project knows about it: \`${cli} why <file>\`. A pre-edit hook stops edits to files
that a decision protects. When it refuses an edit, ask the user in the chat, and run
\`${cli} allow <file>\` only after they agree. Skills: \`projectmind-remember\`,
\`projectmind-why\` and \`projectmind-release-check\`, in \`.agents/skills/\`.
${BLOCK_END}
`;
